version: '3'

services:

  client:
    image: node:latest
    hostname: client
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  server:
    image: node:latest
    hostname: server
    ports:
      - "8081:8081"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  browserless:
    image: browserless/chrome
    hostname: browserless
    environment:
      - PORT=8082
      - HOST=0.0.0.0
      - PREBOOT_CHROME=true
    restart: always
    ports:
      - "8082:8082"

  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:

      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    ports:
      - "8083:8083"
    command: mongod --port 8083